<a href="https://colab.research.google.com/github/OluwoleDove/Csharp_backend/blob/main/numpy_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTING MODULES**

In [87]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**BROADCASTING**

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr = np.arange(10)
print(arr + 5)

[ 5  6  7  8  9 10 11 12 13 14]


In [90]:
arr = np.arange(3)
vect = np.array([1, 2, 3])

arr * vect

array([0, 2, 6])

In [91]:
arr = np.arange(10)
scal = np.array([1, 2, 3])
vect = scal[:, np.newaxis]
print(vect)

arr * vect

[[1]
 [2]
 [3]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

**MULTIDIMENSIONAL ARRAY**

In [92]:
data = [[1, 2, 3], [4, 5, 6]]
arr = np.array(data)
print(arr)
print(f"Shape: {arr.shape}")
print(f"Number of dimensions (ndims): {arr.ndim}")

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions (ndims): 2


In [93]:
data = [(1, 2), (3, 4), (5, 6)]
arr = np.array(data)
print(arr)
print(f"Shape: {arr.shape}")
print(f"Number of dimensions (ndims): {arr.ndim}")

[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)
Number of dimensions (ndims): 2


In [94]:
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**ndims**

In [95]:
arr = np.array([1, 2, 3])
print(f"ndims: {arr.ndim}")

arr1 = np.array([[1, 2], [3, 4]])
print(f"ndims: {arr1.ndim}")

arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"ndims: {arr2.ndim}")

ndims: 1
ndims: 2
ndims: 3


**Special Matrix Functions**

In [96]:
zeros_array = np.zeros((3, 2))
zeros_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
ones_array = np.ones((2, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
empty_array = np.empty((4, 5))
empty_array

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

**ACCESSING ELEMENTS**

In [99]:
arr = np.arange(16).reshape((4, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Indexing**

In [100]:
arr[1, 2] # Access element at row 2, column 3

6

**Slicing**

In [101]:
arr[2:4, 1:]

array([[ 9, 10, 11],
       [13, 14, 15]])

**Boolean Indexing**

In [102]:
mask = arr > 10
arr[mask]

array([11, 12, 13, 14, 15])

**Stylish indexing**

In [103]:
indices = np.array([[0, 2], [1, 3]])
arr[indices]

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

**OPERATIONS**

**Arithmetic Operations**

In [104]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1 + arr2)
print(arr1 * 2)

[[ 6  8]
 [10 12]]
[[2 4]
 [6 8]]


In [105]:
print(np.sqrt(arr1))
print(np.log(arr2))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.60943791 1.79175947]
 [1.94591015 2.07944154]]


**Logical Operators**

In [106]:
print(arr1 > 2)
print(arr2 == arr1)

[[False False]
 [ True  True]]
[[False False]
 [False False]]


#**QUESTION**

Below is a score of 5 students in 3 subjects; Mathematics, Physics and Chemistry respectively

In [107]:
students = 5  # Number of students
subjects = 3  # Number of subjects
scores = np.random.randint(0, 100, size=(students, subjects))
#scores = 100 * np.random.random((students, subjects))

print(scores)

[[82 74 43]
 [65 85 91]
 [11 90 48]
 [57 12  8]
 [ 1 84 64]]


## **Tasks:**

* Create a new array containing only the Mathematics scores for all students.
* Create a new array containing the average score for each student across all subjects.
* Access the score of the first student in Physics.
* Select all scores above 80 in Chemistry.
* Determine the number of dimensions (ndims) in the `scores` array.
* Calculate the total number of scores in the dataset based on the number of dimensions.
* Calculate the difference between each student's highest and lowest score across all subjects.
* Find the subject with the highest average score across all students.
* Explain how broadcasting works when adding a constant value to every element in the `scores` array.
* Discuss potential errors that might arise when working with multidimensional arrays and suggest ways to avoid them.

MATHS SCORE FOR ALL STUDENTS

In [108]:
math_scores = scores[:, 0]
math_scores

array([82, 65, 11, 57,  1])

AVERAGE SCORE PER STUDENT ACROSS EACH SUBJECT

In [109]:
average_scores = np.mean(scores, axis=1)
average_scores

array([66.33333333, 80.33333333, 49.66666667, 25.66666667, 49.66666667])

FIRST ROW STUDENT IN PHYSICS

In [110]:
scores[0, 1]

74

BEST STUDENT IN PHYSICS

In [111]:
np.max(scores[:, 1])

90

ALL SCORES ABOVE 80 IN CHEMISTRY

In [112]:
scores_above_80 = scores[np.where(scores[:, 2] > 80)]
scores_above_80

array([[65, 85, 91]])

NUMBER OF DIMENSIONS OF SCORE

In [113]:
scores.ndim

2

TOTAL NUMBER OF SCORES BASED ON THE NUMBER OF DIMENSIONS

In [114]:
scores.size

15

difference between each student's highest and lowest score across all subjects

In [115]:
# Find the highest score for each student.
highest_scores = np.max(scores, axis=1)

# Find the lowest score for each student.
lowest_scores = np.min(scores, axis=1)

# Subtract the lowest score from the highest score for each student.
differences = highest_scores - lowest_scores

# Print the differences.
print(differences)

[39 26 79 49 83]


subject with the highest average score across all students

In [116]:
average_scores = np.mean(scores, axis=0)  # Calculate average scores for each subject
highest_avg_subject = np.argmax(average_scores)  # Find the index of the highest average score to get the subject

print("Average scores for each subject:", average_scores)
print(f"The subject with the highest average score across all students is subject {highest_avg_subject + 1}")

Average scores for each subject: [43.2 69.  50.8]
The subject with the highest average score across all students is subject 2


## HOW BROADCASTING WORKS

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be used together in arithmetic operations. When you perform an operation between arrays of different shapes or between an array and a constant value, NumPy automatically adjusts their shapes to enable the operation, following a set of rules.

In [117]:
constant_value = 5
result = scores + constant_value
result

array([[87, 79, 48],
       [70, 90, 96],
       [16, 95, 53],
       [62, 17, 13],
       [ 6, 89, 69]])

##MULTIDIMENSIONAL ARRAYS ERRORS & METHODS TO AVOID THEM

Shape Mismatch: Check array shapes before operations.<br />
Indexing Errors: Validate indices to avoid out-of-bounds errors.<br />
Memory Management: Optimize for large arrays to prevent exhaustion.<br />
Data Type Concerns: Ensure consistent data types in operations.<br />
Axis Specification: Specify axes in operations like sum or mean.<br />
Broadcasting Awareness: Understand NumPy's broadcasting rules.<br />
NaNs and Infs: Handle and check for NaNs or Infs after operations.<br /><br />
To avoid: Validate shapes, indices, types, and axes; test and debug step-by-step; optimize for memory; understand broadcasting; handle NaNs and Infs appropriately.

##NUMPY RANDOM FUNCTION

In [118]:
size = 10
np.random.rand(size)

array([0.05993032, 0.97222283, 0.86081537, 0.48385488, 0.13624186,
       0.48211456, 0.21174323, 0.43532578, 0.33976205, 0.74234819])

In [119]:
np.random.rand(10) > 0.5

array([False, False, False,  True, False,  True,  True,  True,  True,
        True])

In [120]:
number = np.random.randint(size)
count = 0
my_guess = 0
while my_guess != number:
  my_guess = int(input("Guess the number: "))
  count += 1
  if my_guess < number:
    print("Guess higher")
  else:
    print("Guess lower")

  if my_guess == number:
    break
print(f"You guess the number in {count} rounds.")

Guess the number: 50
Guess lower
Guess the number: 25
Guess lower
Guess the number: 12
Guess lower
Guess the number: 7
Guess higher
Guess the number: 9
Guess lower
You guess the number in 5 rounds.


In [121]:
np.random.randint(1, 7, 10)

array([6, 4, 4, 2, 2, 3, 2, 2, 5, 3])

In [122]:
'''arr = np.random.choice(["rice", "beans", "yam", "bread", "spaghetti", "wheat"], size=4)
print(arr.astype(str))'''
np.random.choice(["rice", "beans", "yam", "bread", "spaghetti", "wheat"], size=4)

array(['bread', 'wheat', 'bread', 'beans'], dtype='<U9')

In [123]:
np.random.choice(["rice", "beans", "yam", "bread", "spaghetti", "wheat"], size=4, p=[0.1, 0.15, 0.3, 0.05, 0.25, 0.15])

array(['rice', 'yam', 'yam', 'wheat'], dtype='<U9')

In [124]:
occur_dict = {2000:0, 5000:0, 10000:0, 20000:0, 50000:0, 100000:0}
my_wins = np.array(list((occur_dict.keys())))
arr = []
for i in range(20):
  num = np.random.choice(my_wins, size=10, p=[0.55, 0.24, 0.1, 0.07, 0.03, 0.01])
  for j in num:
    for k in range(len(my_wins)):
      if my_wins[k] == j:
        occur_dict[j] += 1
  arr.append(np.sum(num))
  print(num)
print(f"\nTotal amount paid: {np.sum(arr)}\nFrequency: {occur_dict}")

[ 5000 10000  5000  2000  2000  2000  2000  5000  2000  5000]
[ 5000 50000  2000  2000  5000  2000  5000 10000  2000  2000]
[ 2000 20000  2000  2000  2000  2000  2000 10000  2000  2000]
[ 2000  2000  2000  5000 10000  2000 10000  2000  2000  2000]
[ 2000 50000 10000  5000  2000  5000  5000  2000  2000  2000]
[ 5000  5000  5000  2000  2000  5000  2000  2000 20000  2000]
[ 5000  5000  5000  2000 10000 20000  2000  2000  5000  2000]
[ 5000 10000  2000  2000 50000  5000 10000  2000  2000  2000]
[ 2000  5000  5000  5000 20000  2000 10000  5000  5000  2000]
[ 2000  2000 50000 20000  2000  2000  5000  2000  2000  5000]
[ 10000  10000   2000   2000  50000   2000 100000   5000   2000   5000]
[20000 10000  2000  5000  5000 20000  2000  5000 10000  5000]
[2000 2000 2000 2000 5000 2000 2000 5000 5000 2000]
[ 2000  2000  2000  2000  2000 10000  2000  5000  2000  2000]
[10000  2000  2000  5000  2000 10000  5000  2000  5000  5000]
[10000  2000  2000  2000  2000  2000  2000  2000 50000  2000]
[ 2000 5

In [125]:
np.random.choice(["red", "green", "blue"], size=20, replace=True, p=[0.5, 0.3, 0.2])

array(['red', 'red', 'blue', 'red', 'red', 'green', 'red', 'blue', 'blue',
       'blue', 'green', 'red', 'red', 'blue', 'green', 'blue', 'red',
       'blue', 'green', 'red'], dtype='<U5')

#FILTER

In [126]:
random_integers = np.arange(100)
filtered_elements = np.where(random_integers % 2 == 0)
filtered_elements

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
        68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]),)

In [127]:
np.random.choice(np.array(list(filtered_elements)).squeeze(), size=10)

array([ 0, 72, 50, 46, 42, 28, 62, 10, 16, 50])

In [128]:
prime_indices = np.where(np.logical_and(random_integers % 2 != 0, random_integers > 8))
print(prime_indices)

(array([ 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41,
       43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75,
       77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),)


## **CLASS WORK AND INTRODUCING PANDAS**

##Importing Modules & Reading Data

In [129]:
import numpy as np
import pandas as pd
from numpy import random
# Load the dataset
df = pd.read_csv("dataset/textseries.csv")
df.dropna(inplace = True)
df.head()

text  humor
0  Joe biden rules out 2020 bid: 'guys, i'm not r...  False
1  Watch: darvish gave hitter whiplash with slow ...  False
2  What do you call a turtle without its shell? d...   True
3      5 reasons the 2016 election feels so personal  False
4  Pasco police shot mexican migrant from behind,...  False

In [130]:
df.describe()

text   humor
count                                              200000  200000
unique                                             200000       2
top     Joe biden rules out 2020 bid: 'guys, i'm not r...   False
freq                                                    1  100000

##FILTERING DATAFRAME

In [131]:
data = df.loc[df['text'].str.contains('Why') | df['text'].str.contains('What')]
data.groupby(['humor']).count()
data.describe()

text  humor
count                                               38085  38085
unique                                              38085      2
top     What do you call a turtle without its shell? d...   True
freq                                                    1  35005

#DERIVING ARRAYS FROM DATAFRAME

In [132]:
new_array = data.to_numpy()
new_array

array([['What do you call a turtle without its shell? dead.', True],
       ["What is a pokemon master's favorite kind of pasta? wartortellini!",
        True],
       ['Why do native americans hate it when it rains in april? because it brings mayflowers.',
        True],
       ...,
       ["Why did reddit's restaurant go our of business? all of its servers were busy",
        True],
       ['What is it called when batman skips church? .....christian bale.',
        True],
       ["What did the child with no arms get for christmas? gloves. just kidding, he hasn't opened it yet.",
        True]], dtype=object)

In [133]:
np.ndim(new_array)

2

In [143]:
true_array = []
false_array = []
my_array = []
for i in new_array:
    if i[-1] == True:
        true_array.append(i[0])
    else:
        false_array.append(i[0])

my_array.append(true_array)
my_array.append(false_array)

## **FINAL OUTCOME**

In [142]:
my_joke = random.choice(random.choice(my_array, p=[len(true_array)/len(new_array), 1 - (len(true_array)/len(new_array))]))
if my_joke in true_array:
    print(f'{my_joke} IS HUMOROUS')
else:
    print(f'{my_joke} is NOT HUMOROUS')

What i lack in social skills, i make up for in hiding-from-people skills. IS HUMOROUS


<ipython-input-142-5ddce163db2a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  my_joke = random.choice(random.choice(my_array, p=[len(true_array)/len(new_array), 1 - (len(true_array)/len(new_array))]))
