<a href="https://colab.research.google.com/github/OluwoleDove/Csharp_backend/blob/main/numpy_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTING MODULES**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**BROADCASTING**

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(10)
print(arr + 5)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr = np.arange(3)
vect = np.array([1, 2, 3])

arr * vect

array([0, 2, 6])

In [ ]:
arr = np.arange(10)
scal = np.array([1, 2, 3])
vect = scal[:, np.newaxis]
print(vect)

arr * vect

[[1]
 [2]
 [3]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]])

**MULTIDIMENSIONAL ARRAY**

In [ ]:
data = [[1, 2, 3], [4, 5, 6]]
arr = np.array(data)
print(arr)
print(f"Shape: {arr.shape}")
print(f"Number of dimensions (ndims): {arr.ndim}")

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions (ndims): 2


In [ ]:
data = [(1, 2), (3, 4), (5, 6)]
arr = np.array(data)
print(arr)
print(f"Shape: {arr.shape}")
print(f"Number of dimensions (ndims): {arr.ndim}")

[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)
Number of dimensions (ndims): 2


In [ ]:
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**ndims**

In [ ]:
arr = np.array([1, 2, 3])
print(f"ndims: {arr.ndim}")

arr1 = np.array([[1, 2], [3, 4]])
print(f"ndims: {arr1.ndim}")

arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"ndims: {arr2.ndim}")

ndims: 1
ndims: 2
ndims: 3


**Special Matrix Functions**

In [ ]:
zeros_array = np.zeros((3, 2))
zeros_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ones_array = np.ones((2, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
empty_array = np.empty((4, 5))
empty_array

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

**ACCESSING ELEMENTS**

In [ ]:
arr = np.arange(16).reshape((4, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Indexing**

In [ ]:
arr[1, 2] # Access element at row 2, column 3

6

**Slicing**

In [ ]:
arr[2:4, 1:]

array([[ 9, 10, 11],
       [13, 14, 15]])

**Boolean Indexing**

In [ ]:
mask = arr > 10
arr[mask]

array([11, 12, 13, 14, 15])

**Stylish indexing**

In [ ]:
indices = np.array([[0, 2], [1, 3]])
arr[indices]

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

**OPERATIONS**

**Arithmetic Operations**

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1 + arr2)
print(arr1 * 2)

[[ 6  8]
 [10 12]]
[[2 4]
 [6 8]]


In [ ]:
print(np.sqrt(arr1))
print(np.log(arr2))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.60943791 1.79175947]
 [1.94591015 2.07944154]]


**Logical Operators**

In [ ]:
print(arr1 > 2)
print(arr2 == arr1)

[[False False]
 [ True  True]]
[[False False]
 [False False]]


#**QUESTION**

Below is a score of 5 students in 3 subjects; Mathematics, Physics and Chemistry respectively

In [ ]:
students = 5  # Number of students
subjects = 3  # Number of subjects
scores = np.random.randint(0, 100, size=(students, subjects))
#scores = 100 * np.random.random((students, subjects))

print(scores)

[[19 16 32]
 [91 96 90]
 [24 93 58]
 [ 5  2 18]
 [32 45  5]]


## **Tasks:**

* Create a new array containing only the Mathematics scores for all students.
* Create a new array containing the average score for each student across all subjects.
* Access the score of the first student in Physics.
* Select all scores above 80 in Chemistry.
* Determine the number of dimensions (ndims) in the `scores` array.
* Calculate the total number of scores in the dataset based on the number of dimensions.
* Calculate the difference between each student's highest and lowest score across all subjects.
* Find the subject with the highest average score across all students.
* Explain how broadcasting works when adding a constant value to every element in the `scores` array.
* Discuss potential errors that might arise when working with multidimensional arrays and suggest ways to avoid them.

MATHS SCORE FOR ALL STUDENTS

In [ ]:
math_scores = scores[:, 0]
math_scores

array([19, 91, 24,  5, 32])

AVERAGE SCORE PER STUDENT ACROSS EACH SUBJECT

In [ ]:
average_scores = np.mean(scores, axis=1)
average_scores

array([22.33333333, 92.33333333, 58.33333333,  8.33333333, 27.33333333])

FIRST ROW STUDENT IN PHYSICS

In [ ]:
scores[0, 1]

16

BEST STUDENT IN PHYSICS

In [ ]:
np.max(scores[:, 1])

96

ALL SCORES ABOVE 80 IN CHEMISTRY

In [ ]:
scores_above_80 = scores[np.where(scores[:, 2] > 80)]
scores_above_80

array([[91, 96, 90]])

NUMBER OF DIMENSIONS OF SCORE

In [ ]:
scores.ndim

2

TOTAL NUMBER OF SCORES BASED ON THE NUMBER OF DIMENSIONS

In [ ]:
scores.size

15

difference between each student's highest and lowest score across all subjects

In [ ]:
# Find the highest score for each student.
highest_scores = np.max(scores, axis=1)

# Find the lowest score for each student.
lowest_scores = np.min(scores, axis=1)

# Subtract the lowest score from the highest score for each student.
differences = highest_scores - lowest_scores

# Print the differences.
print(differences)

[16  6 69 16 40]


subject with the highest average score across all students

In [ ]:
average_scores = np.mean(scores, axis=0)  # Calculate average scores for each subject
highest_avg_subject = np.argmax(average_scores)  # Find the index of the highest average score to get the subject

print("Average scores for each subject:", average_scores)
print(f"The subject with the highest average score across all students is subject {highest_avg_subject + 1}")

Average scores for each subject: [34.2 50.4 40.6]
The subject with the highest average score across all students is subject 2


## HOW BROADCASTING WORKS

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be used together in arithmetic operations. When you perform an operation between arrays of different shapes or between an array and a constant value, NumPy automatically adjusts their shapes to enable the operation, following a set of rules.

In [ ]:
constant_value = 5
result = scores + constant_value
result

array([[ 24,  21,  37],
       [ 96, 101,  95],
       [ 29,  98,  63],
       [ 10,   7,  23],
       [ 37,  50,  10]])

##MULTIDIMENSIONAL ARRAYS ERRORS & METHODS TO AVOID THEM

Shape Mismatch: Check array shapes before operations.<br />
Indexing Errors: Validate indices to avoid out-of-bounds errors.<br />
Memory Management: Optimize for large arrays to prevent exhaustion.<br />
Data Type Concerns: Ensure consistent data types in operations.<br />
Axis Specification: Specify axes in operations like sum or mean.<br />
Broadcasting Awareness: Understand NumPy's broadcasting rules.<br />
NaNs and Infs: Handle and check for NaNs or Infs after operations.<br /><br />
To avoid: Validate shapes, indices, types, and axes; test and debug step-by-step; optimize for memory; understand broadcasting; handle NaNs and Infs appropriately.